import { normalizeDesktopMenuLocale, type DesktopMenuLocale } from "@opencode-ai/app/desktop-menu"
import type { Labels } from "electron-context-menu"

const labels = {
  en: {
    learnSpelling: "Learn Spelling",
    lookUpSelection: "Look Up “{selection}”",
    searchWithGoogle: "Search with Google",
    cut: "Cut",
    copy: "Copy",
    paste: "Paste",
    selectAll: "Select All",
    saveImage: "Save Image",
    saveImageAs: "Save Image As…",
    saveVideo: "Save Video",
    saveVideoAs: "Save Video As…",
    copyLink: "Copy Link",
    saveLinkAs: "Save Link As…",
    copyImage: "Copy Image",
    copyImageAddress: "Copy Image Address",
    copyVideoAddress: "Copy Video Address",
    inspect: "Inspect Element",
    services: "Services",
  },
  zh: {
    learnSpelling: "学习拼写",
    lookUpSelection: "查询“{selection}”",
    searchWithGoogle: "使用 Google 搜索",
    cut: "剪切",
    copy: "复制",
    paste: "粘贴",
    selectAll: "全选",
    saveImage: "保存图像",
    saveImageAs: "图像另存为...",
    saveVideo: "保存视频",
    saveVideoAs: "视频另存为...",
    copyLink: "复制链接",
    saveLinkAs: "链接另存为...",
    copyImage: "复制图像",
    copyImageAddress: "复制图像地址",
    copyVideoAddress: "复制视频地址",
    inspect: "检查元素",
    services: "服务",
  },
  zht: {
    learnSpelling: "學習拼寫",
    lookUpSelection: "查詢“{selection}”",
    searchWithGoogle: "使用 Google 搜尋",
    cut: "剪下",
    copy: "複製",
    paste: "貼上",
    selectAll: "全選",
    saveImage: "儲存圖像",
    saveImageAs: "圖像另存為...",
    saveVideo: "儲存影片",
    saveVideoAs: "影片另存為...",
    copyLink: "複製連結",
    saveLinkAs: "連結另存為...",
    copyImage: "複製圖像",
    copyImageAddress: "複製圖像位址",
    copyVideoAddress: "複製影片位址",
    inspect: "檢查元素",
    services: "服務",
  },
} satisfies Record<DesktopMenuLocale, Required<Labels>>

export function createContextMenuLabels(locale: string): Required<Labels> {
  return { ...labels[normalizeDesktopMenuLocale(locale)] }
}
